site_name: x86prime
nav:
    - Home: index.md
    - x86prime: x86prime.md
    - Afviklingsplot:
        - Introduktion: afviklingsplot/index.md
        - Simpel pipeline: afviklingsplot/pipeline.md
        - Superskalar: afviklingsplot/superscalar.md
        - Avanceret pipeline, anonyme faser: afviklingsplot/anonyme.md
        - Out-of-order: afviklingsplot/out-of-order.md
        - Kontrol afh√¶ngigheder: afviklingsplot/kontrol.md
# theme: readthedocs
theme: material
extra_css:
    - css/extra.css
plugins:
    - search
    # - pdf-export
    - pdf-export:
        verbose: true
        media_type: print
        enabled_if_env: ENABLE_PDF_EXPORT
